Patch 1
spatie/laravel-searchable pull request #101
Opened 2021-01-19 17:49 UTC by voydz

PR for issue #100 

This basically just changes the order of when internal search attributes and forwardedCalls being added to the query builder.

2021-05-03 09:31 UTC, freekmurze commented
Could you rebase this against the current master?

2021-05-04 08:26 UTC, voydz commented
@freekmurze no problem

do not mind the force push 👀 

I forgot to actually modify the added tests to reflect changes in #110

2021-05-04 08:35 UTC, freekmurze requested changes

2021-05-04 08:35 UTC, freekmurze commented on .php_cs.cache
> +{"php":"8.0.5","version":"2.18.6","indent":"    ","lineEnding":"\n","rules":{"blank_line_after_namespace":true,"braces":true,"class_definition":true,"constant_case":true,"elseif":true,"function_decla
This file may be deleted an ignored

2021-05-04 08:38 UTC, merged

2021-05-04 08:38 UTC, freekmurze commented
Thanks!